version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "viamin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "viamin"
