sqlite3: &sqlite3
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: seed-migration-<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: seed-migration-<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV.fetch('DB', "sqlite3") %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
